"""feat: agent_insights table

Revision ID: 79fc5d14d405
Revises: ef95b5ed67de
Create Date: 2026-04-20 19:38:03.605325

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79fc5d14d405"
down_revision: str | None = "ef95b5ed67de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_insights",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("agent_type", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("model_used", sa.String(length=50), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_insights_agent_type"), "agent_insights", ["agent_type"], unique=False
    )
    op.create_index(
        op.f("ix_agent_insights_created_at"), "agent_insights", ["created_at"], unique=False
    )
    op.create_index(
        "ix_agent_insights_user_agent_created",
        "agent_insights",
        ["user_id", "agent_type", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_agent_insights_user_id"), "agent_insights", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_insights_user_id"), table_name="agent_insights")
    op.drop_index("ix_agent_insights_user_agent_created", table_name="agent_insights")
    op.drop_index(op.f("ix_agent_insights_created_at"), table_name="agent_insights")
    op.drop_index(op.f("ix_agent_insights_agent_type"), table_name="agent_insights")
    op.drop_table("agent_insights")
    # ### end Alembic commands ###
